### PR TITLE
Support Bugsnag 6.26.2 and above

### PR DESCRIPTION
**Pull request by rickclephas**

### CODE REVIEW

**Comment by kpgalligan** [comment]
Huh. Did bugsnag break something?

**Comment by rickclephas** [comment]
Yeah they no longer use `unhandled` to determine if the exception should be saved to disk instead of being send immediately.  Based on my tests all exception are lost with Bugsnag 2.26.2 or above, due to the immediate termination of the app. Had to "override" the new `originalUnhandledValue` property to workaround their updated check 😅.

**Comment by rickclephas** [comment]
Specifically the following change broke our unhandled exception recording: https://github.com/bugsnag/bugsnag-cocoa/pull/1549

**Comment by rickclephas** [comment]
FYI opened a feature request for an officially support API: https://github.com/bugsnag/bugsnag-cocoa/issues/1575.

**Pull request merged**
